---
config:
  flowchart:
    htmlLabels: false
---

flowchart LR
    view["View"]
    viewModel["ViewModel"]
    component["Component"]
    dto["DTO"]
    view --> viewModel --> dto --> component
    
